In [61]:
import numpy as np

X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)
print(X)
print(Y)

TypeError: data type not understood

In [55]:
print(X + Y)
print(np.sqrt(X))

[[ 6.5  8.5]
 [10.5 12.5]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [56]:
print('Average of all elements in X:', X.mean())

Average of all elements in X: 2.5


In [57]:
print('3 * X = \n', 3 * X)

3 * X = 
 [[ 3  6]
 [ 9 12]]


In [59]:
Z = np.ones((4,4))
T = np.arange(1,5)
print(Z)
print(T)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1 2 3 4]


In [60]:
print(Z * T)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [62]:
X = np.random.random((3,3))
print(X)

[[0.58808025 0.37280903 0.01646033]
 [0.86711206 0.64734335 0.06395987]
 [0.41665343 0.43041002 0.84235359]]


In [63]:
X = np.random.randint(4,15,size=(3,2))
print(X)

[[ 5 14]
 [ 9  4]
 [ 6 13]]


In [64]:
!conda list pandas

# packages in environment at /Users/xinxi/anaconda3:
#
# Name                    Version                   Build  Channel
pandas                    0.23.1           py36h1702cab_0  
